[project]
name = "ai-with-jupyter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fitz>=0.0.1.dev2",
    "frontend>=0.0.3",
    "jupyter-resource-usage>=1.1.1",
    "langchain>=0.3.25",
    "matplotlib>=3.10.3",
    "mistralai>=1.8.2",
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "polars>=1.30.0",
    "python-dotenv>=1.1.0",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
]
